import Foundation

/// Comprehensive database of agave spirit brands available in the U.S.
/// Sourced from Mezcalistas (updated 2025-08-27) and major retailer catalogs.
/// Includes mezcal, sotol, bacanora, and raicilla brands.
/// Users can always type a custom brand not on this list.
enum MezcalBrands {

    // MARK: - Mezcal / Destilado de Agave

    static let mezcal: [String] = [
        "3000 Noches",
        "400 Conejos",
        "5 Sentidos",
        "Acre Mezcal",
        "Agave de Cortes",
        "Agua del Sol",
        "Agua Mágica",
        "Aguerrido",
        "Akul Mezcal",
        "Alacran",
        "Alipus",
        "Almamezcalera",
        "Alto Cielo",
        "Amarás",
        "Amateco",
        "Aprendiz",
        "Banhez",
        "Beneficio Viejo",
        "Benesin",
        "Bosscal",
        "Bozal",
        "Bruxo",
        "Buen Bicho",
        "Caballito Cerrero",
        "Campanilla del Palmar",
        "Campante Mezcal",
        "Carreño Mezcal",
        "Casa Pineda",
        "Casta Tribal",
        "Catedral de mi Padre",
        "Celebrante",
        "Chacolo",
        "Chapu Mezcal",
        "Cinco Sentidos",
        "Claridad",
        "Comunidad",
        "Convite Mezcal",
        "Creador Agave Spirits",
        "Cruz de Fuego",
        "Cuentacuentos",
        "CUISH",
        "de Matachines",
        "Del Maguey",
        "Derrumbes",
        "Desolas",
        "Divino Maguey",
        "Dixeebe",
        "Don Amado",
        "Don Mateo de la Sierra",
        "Donají",
        "Doña Perla",
        "Doña Vega",
        "Dos Boots",
        "Dos Hombres",
        "Dos Pasiones",
        "el Buho",
        "el Guel Mezcal",
        "El Jolgorio",
        "El Mero Mero",
        "El Pelotón de la Muerte",
        "El Rey Zapoteco",
        "El Samaritano",
        "El Sarao",
        "El Silencio",
        "El Tigre",
        "El Tinieblo",
        "Enmascarado",
        "Erstwhile Mezcal",
        "Esfuerzo Mezcal",
        "Espina Negra",
        "Espina Roja",
        "Espiritu Lauro",
        "Estacion Ipiña",
        "FaneKantsini",
        "Fidencio",
        "Firme Mezcal",
        "Fósforo Mezcal",
        "Fuego y Humo",
        "Gem & Bolt",
        "Gente de Mezcal",
        "Geu Beez Mezcal",
        "Gracias a Dios",
        "Grulani Mezcal",
        "Gusto Historico",
        "Hacienda Oponguio",
        "Huxal Mezcal",
        "Illegal",
        "IZO Mezcal",
        "Jaral de Berrio",
        "Joya",
        "Júrame",
        "Koch",
        "La Herencia de Sanchez",
        "La Jicarita",
        "La Medida Mezcal",
        "La Luna Mezcal",
        "La Niña del Mezcal",
        "La Remilgosa",
        "La Venia Mezcal",
        "Lagrimas de Dolores",
        "Lalocura",
        "Lamata",
        "Legendario Domingo",
        "Lejana y Sol",
        "Lopez Real Mezcal",
        "Los Amantes",
        "Los Cantiles 1905",
        "Los Danzantes",
        "Los Javis",
        "Los Nahuales",
        "Los Ocotales",
        "Los Vecinos del Campo",
        "Lost Explorer Mezcal",
        "Lucy Pistolas",
        "Luneta",
        "Machetazo",
        "Macurichos",
        "Madre Mezcal",
        "Mal de Amor",
        "Marca Negra",
        "Matasanta Mezcal",
        "Mayalen",
        "Mezcal Animas",
        "Mezcal Burrito Fiestero",
        "Mezcal Chulele",
        "Mezcal Complice",
        "Mezcal Craneo",
        "Mezcal de Leyendas",
        "Mezcal Desde la Eternidad",
        "Mezcal Exiliado",
        "Mezcal Guey",
        "Mezcal Local",
        "Mezcal Magia Pura",
        "Mezcal Mal Bien",
        "Mezcal Marqués",
        "Mezcal Nacional",
        "Mezcal Rambhá",
        "Mezcal Shot Bala 50",
        "Mezcal Tileño",
        "Mezcal Trascedente",
        "Mezcal Union",
        "Mezcal Villasuso",
        "Mezcalero",
        "Mezcalosfera",
        "Mezcasiarca",
        "Mezonte",
        "Mi Gusto Es",
        "Mil Lumbres",
        "Mina Real",
        "Mocel Mezcal",
        "Montelobos",
        "Morro Mezcal",
        "NETA Spirits",
        "Noble Coyote Mezcal",
        "Nuestra Soledad",
        "OAX Original",
        "Ojo de Tigre",
        "Origen Raiz",
        "Pal'Alma",
        "Palenqueros",
        "Palomas Mensajeras",
        "Paquera",
        "Parejo",
        "Patatús",
        "Perro Verde",
        "Pierde Almas",
        "Pluma Negra",
        "Prolijo Mezcal",
        "Puntagave",
        "Puntamanguera Mezcal",
        "Puntiagudo",
        "Quiquiriqui",
        "Rancho Tepua",
        "Rayo Seco",
        "Real Minero",
        "Rey Campero",
        "Rezpiral",
        "Rosaluna",
        "Sacro Imperio",
        "Sacacuento",
        "Sacrificio",
        "Salvadores",
        "San Bartolo",
        "San Cosme",
        "Santa Pedrera",
        "Sanzekan",
        "Scorpion Mezcal",
        "Semillero",
        "Señor Mezcalero",
        "Siembra Metl",
        "Siete Misterios",
        "Sol de Oaxaca",
        "Soluro 1610",
        "Sombra",
        "Susto Mezcal",
        "Tepenal Mezcal",
        "The Moon Shift",
        "The Producer",
        "Tio Pesca",
        "Tlamati Spirits",
        "Tomas Artesanal Mezcal",
        "Tosba",
        "Tres Tiempos",
        "Tres Tribus Mezcal",
        "Ultramundo",
        "Unito",
        "Vago",
        "Vamanos Riendo",
        "Vicio",
        "Viejo Indecente",
        "Vinos de Mezcal",
        "Wahaka",
        "Xicaru Mezcal",
        "Yola Mezcal",
        "Yuku Savi",
        "Yuu Baal",
        "Zancudo Mezcal",
        "Zinacantan",
        "Zomoz Mezcal",
    ]

    // MARK: - Sotol

    static let sotol: [String] = [
        "Acrónimo Sotol",
        "Cardenxe Sotol",
        "Clande Sotol",
        "Flor del Desierto Sotol",
        "Guerra Seca Sotol",
        "Hacienda de Chihuahua Sotol",
        "Ocho Cientos Sotol",
        "Sotoleros",
    ]

    // MARK: - Bacanora

    static let bacanora: [String] = [
        "Batuq Bacanora",
        "Cielo Rojo Bacanora",
        "Kilinga Bacanora",
        "Mazot Bacanora",
        "Santo Cuviso Bacanora",
        "Sunora Bacanora",
        "YooWe Bacanora",
    ]

    // MARK: - Raicilla

    static let raicilla: [String] = [
        "Balam Raicilla",
        "Bonete Raicilla",
        "La Reina de Atenguillo Raicilla",
        "Raicilla de Una",
        "Raicilla La Venenosa",
    ]

    // MARK: - Combined

    /// All brands across all agave spirit categories
    static let all: [String] = (mezcal + sotol + bacanora + raicilla).sorted()

    /// Returns brands matching a search query, case-insensitive
    static func suggestions(for query: String) -> [String] {
        guard !query.trimmingCharacters(in: .whitespaces).isEmpty else { return [] }
        return all.filter { $0.localizedCaseInsensitiveContains(query) }
    }

    /// Returns brands matching a query within a specific category
    static func suggestions(for query: String, category: String) -> [String] {
        guard !query.trimmingCharacters(in: .whitespaces).isEmpty else { return [] }
        let source: [String]
        switch category.lowercased() {
        case "sotol": source = sotol
        case "bacanora": source = bacanora
        case "raicilla": source = raicilla
        default: source = all
        }
        return source.filter { $0.localizedCaseInsensitiveContains(query) }
    }
}
